In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Bounding boxes for YOLO classification model

In [3]:
import pandas as pd
path = '/content/drive/MyDrive/Colab Notebooks/DF20M-metadata/'
test_df = pd.read_csv(path + 'DF20M-public_test_metadata_PROD.csv')

In [4]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3640 entries, 0 to 3639
Data columns (total 33 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   gbifID                3640 non-null   int64
 1   eventDate             3639 non-null   object
 2   year                  3639 non-null   float64
 3   month                 3639 non-null   float64
 4   day                   3639 non-null   float64
 5   countryCode           3640 non-null   object
 6   locality              3636 non-null   object
 7   taxonID               3640 non-null   float64
 8   scientificName        3640 non-null   object
 9   kingdom               3640 non-null   object
 10  phylum                3640 non-null   object
 11  class                 3640 non-null   object
 12  order                 3640 non-null   object
 13  family                3640 non-null   object
 14  genus                 3640 non-null   object
 15  specificEpithet       3640 non-null   object
 16  infraspecificEpithet  0 non-null      float64
 17  taxonRank             3640 non-null   object
 18  species               3637 non-null   object
 19  level0Gid             3634 non-null   object
 20  level0Name            3634 non-null   object
 21  level1Gid             3634 non-null   object
 22  level1Name            3634 non-null   object
 23  level2Gid             3634 non-null   object
 24  level2Name            3634 non-null   object
 25  ImageUniqueID         3640 non-null   object
 26  Substrate             3624 non-null   object
 27  rightsHolder          3640 non-null   object
 28  Latitude              3640 non-null   float64
 29  Longitude             3640 non-null   float64
 30  CoorUncert            3584 non-null   float64
 31  Habitat               3627 non-null   object
 32  image_path            3640 non-null   object
dtypes: float64(8), int64(1), object(24)
memory usage: 938.6+ KB

In [5]:
test_df.head()

,gbifID,eventDate,year,month,day,countryCode,locality,taxonID,scientificName,kingdom,...,level2Gid,level2Name,ImageUniqueID,Substrate,rightsHolder,Latitude,Longitude,CoorUncert,Habitat,image_path
0,2238504270,2017-08-20T00:00:00,2017.0,8.0,20.0,DK,Store Dyrehave,20020.0,Russula nigricans (Bull.) Fr.,Fungi,...,DNK.1.20_1,Hillerød,2238504270-171705,soil,Dan Ingemann Jensen,55.905585,12.362367,75.0,Deciduous woodland,2238504270-171705.JPG
1,2238511676,2017-09-17T00:00:00,2017.0,9.0,17.0,DK,Store Hareskov,17238.0,Mycena haematopus (Pers.) P.Kumm.,Fungi,...,DNK.1.12_1,Furesø,2238511676-246956,dead wood (including bark),Tarquin Netherway,55.769675,12.401108,15.0,Deciduous woodland,2238511676-246956.JPG
2,2883271536,2020-10-18T00:00:00,2020.0,10.0,18.0,DK,Lillerød,17289.0,Mycena rosea (Schumach.) Gramberg,Fungi,...,DNK.1.2_1,Allerød,2883271536-291057,soil,Dan Ingemann Jensen,55.878946,12.359130,40.0,Deciduous woodland,2883271536-291057.JPG
3,2446759186,2019-10-26T00:00:00,2019.0,10.0,26.0,DK,Ollerup,10079.0,Agaricus impudicus (Rea) Pilát,Fungi,...,DNK.5.18_1,Svendborg,2446759186-271681,soil,Dan Schou,55.068441,10.515358,50.0,Unmanaged deciduous woodland,2446759186-271681.JPG
4,2382321410,2019-08-30T00:00:00,2019.0,8.0,30.0,DK,"Dyrehave, Valdemars Slot (inkl Pederskov)",19939.0,Russula chloroides (Krombh.) Bres.,Fungi,...,DNK.5.18_1,Svendborg,2382321410-191132,soil,Kirsten Bjørnsson,55.013310,10.644585,75.0,Deciduous woodland,2382321410-191132.JPG

In [6]:
print(f"Unique species: {test_df['scientificName'].nunique()}")

Унікальних видів: 182

In [7]:
print(test_df['scientificName'].unique()[:10])

['Russula nigricans (Bull.) Fr.' 'Mycena haematopus (Pers.) P.Kumm.'
 'Mycena rosea (Schumach.) Gramberg' 'Agaricus impudicus (Rea) Pilát'
 'Russula chloroides (Krombh.) Bres.' 'Amanita rubescens (Pers.) Gray'
 'Russula vesca Fr.' 'Agaricus arvensis Schaeff.' 'Boletus edulis Bull.'
 'Russula violeipes Quél.']

In [8]:
#dict for poison/not poison mushrooms. 0 - not poison, 1 - poison
mushrooms_map = {
    'Russula cyanoxantha (Schaeff.) Fr.': 0, 'Russula ochroleuca (Pers.) Fr.': 0, 'Infundibulicybe gibba (Pers.) Harmaja': 0, 'Clitocybe nebularis (Batsch) Quél.': 0,
    'Agaricus essettei Bon': 0, 'Infundibulicybe costata (Kühner & Romagn.) Harmaja': 0, 'Agaricus campestris L.': 0, 'Agaricus augustus Fr.': 0,
    'Amanita submembranacea (Bon) Gröger': 0, 'Russula odorata Romagn.': 0, 'Russula faginea Romagn., 1967': 0, 'Amanita excelsa Gonn. & Rabenh.': 0,
    'Russula velenovskyi Melzer & Zvára': 0, 'Agaricus cupreobrunneus (Jul.Schäff. & Steer) Pilát': 0, 'Russula aurea Pers.': 0, 'Russula melliolens Quél.': 0,
    'Russula delica Fr.': 0, 'Agaricus langei (F.H.Møller & Jul.Schäff.) Maire': 0, 'Boletus aereus Secr.': 0, 'Russula ionochlora Romagn.': 0,
    'Amanita lividopallescens (Secr. ex Boud.) Kühner & Romagn.': 0, 'Agaricus litoralis (Wakef. & A.Pearson) Pilát': 0, 'Amanita strobiliformis Gonn. & Rabenh.': 0,
    'Russula nitida (Pers.) Fr.': 0, 'Russula velutipes Velen.': 0, 'Agaricus bisporus (J.E.Lange) Pilat': 0, 'Russula virescens (Schaeff.) Fr.': 0, 'Russula claroflava Grove':0,
    'Russula grisea (Batsch) Fr.': 0, 'Russula xerampelina (Schaeff.) Fr.': 0, 'Amanita vaginata (Bull.) Vittad.': 0, 'Amanita crocea (Quél.) Singer': 0, 'Russula depallens Fr.':0,
    'Agaricus subperonatus (J.E.Lange) Singer': 0, 'Russula integra (L.) Fr., 1838': 0, 'Agaricus crocodilinus Murrill': 0, 'Russula parazurea Jul.Schäff.': 0,
    'Agaricus bernardii (Quél.) Sacc.': 0, 'Amanita ceciliae (Berk. & Broome) Bas': 0, 'Russula cessans A.Pearson': 0, 'Agaricus sylvicola (Vittad.) Peck, 1872': 0,
    'Russula paludosa Britzelm.': 0, 'Xerocomus subtomentosus (L.) Fr.': 0, 'Agaricus bitorquis (Quél.) Sacc.': 0, 'Russula olivacea (Schaeff.) Fr.': 0, 'Russula adusta (Pers.) Fr.': 0,
    'Infundibulicybe squamulosa (Pers.) Harmaja': 0, 'Agaricus dulcidulus Schulzer': 0, 'Russula graveolens Romell': 0, 'Russula risigallina (Batsch) Sacc.': 0,
    'Russula aeruginea Fr.': 0, 'Clitocybe odora (Bull.) P.Kumm.': 0, 'Russula heterophylla (Fr.) Fr.': 0, 'Russula puellaris Fr.': 0, 'Russula romellii Maire': 0,
    'Boletus pinophilus Pilát & Dermek': 0, 'Russula seperina Dupain': 0, 'Russula brunneoviolacea Crawshay': 0, 'Russula laeta Jul.Schäff.': 0, 'Russula decolorans (Fr.) Fr.': 0,
    'Agaricus bohusii Bon': 0, 'Agaricus subfloccosus (J.E.Lange) Pilát': 0, 'Russula curtipes F.H.Møller & Jul.Schäff.': 0, 'Russula caerulea (Pers.) Fr.': 0,
    'Russula subrubens (J.E.Lange) Bon': 0, 'Agaricus brunneolus (J.E.Lange) Pilát': 0, 'Russula faustiana Sarnari': 0, 'Agaricus lanipes (F.H.Møller & Jul.Schäff.) Singer': 0
}

In [9]:
def mushroom_category(name):
  return mushrooms_map.get(name, 1)

In [10]:
test_df['mushroom_label'] = test_df['scientificName'].apply(mushroom_category)

In [11]:
print(test_df[['scientificName', 'mushroom_label']])

                             scientificName  mushroom_label
0             Russula nigricans (Bull.) Fr.               1
1         Mycena haematopus (Pers.) P.Kumm.               1
2         Mycena rosea (Schumach.) Gramberg               1
3            Agaricus impudicus (Rea) Pilát               1
4        Russula chloroides (Krombh.) Bres.               1
...                                     ...             ...
3635                   Boletus edulis Bull.               1
3636         Mycena pelianthina (Fr.) Quél.               1
3637  Clitocybe phyllophila (Pers.) P.Kumm.               1
3638           Amanita fulva (Schaeff.) Fr.               1
3639   Mycena galopus (Pers.) P.Kumm., 1871               1

[3640 rows x 2 columns]

In [12]:
test_df.sample(10)

,gbifID,eventDate,year,month,day,countryCode,locality,taxonID,scientificName,kingdom,...,level2Name,ImageUniqueID,Substrate,rightsHolder,Latitude,Longitude,CoorUncert,Habitat,image_path,mushroom_label
3358,2413148079,2019-09-10T00:00:00,2019.0,9.0,10.0,DK,Søgård,11772.0,Infundibulicybe gibba (Pers.) Harmaja,Fungi,...,Vejle,2413148079-117970,soil,Ken A. Alminde,55.671813,9.334409,25.0,Deciduous woodland,2413148079-117970.JPG,0
2548,2964219385,2020-11-04T00:00:00,2020.0,11.0,4.0,DK,Græsmark Skov,17218.0,Mycena diosma Krieglst. & Schwöbel,Fungi,...,Køge,2964219385-219352,leaf or needle litter,Benny T. Olsen,55.464891,12.091836,50.0,Deciduous woodland,2964219385-219352.JPG,1
3047,2862693409,2020-09-14T00:00:00,2020.0,9.0,14.0,DK,Rude Skov,11061.0,Boletus aereus Secr.,Fungi,...,Slagelse,2862693409-137193,soil,Yvonne Engmann,55.207431,11.489520,75.0,Unmanaged deciduous woodland,2862693409-137193.JPG,0
3361,2238572300,2018-10-09T00:00:00,2018.0,10.0,9.0,DK,Læsø,10252.0,"Amanita muscaria (L.) Lam., 1783",Fungi,...,Læsø,2238572300-184228,soil,Per Taudal Poulsen,57.271862,10.972707,25.0,Mixed woodland (with coniferous and deciduous ...,2238572300-184228.JPG,1
2494,2812994326,2020-07-08T00:00:00,2020.0,7.0,8.0,DK,Hjøllund,63479.0,Amanita rubescens (Pers.) Gray,Fungi,...,Silkeborg,2812994326-282161,soil,Frits Sørensen,56.077836,9.356931,15.0,Unmanaged coniferous woodland,2812994326-282161.JPG,1
1718,2427872033,2019-10-15T00:00:00,2019.0,10.0,15.0,DK,Øksenrade Skov,63482.0,Clitocybe nebularis (Batsch) Quél.,Fungi,...,Middelfart,2427872033-46889,soil,Jacob Lindhardt Palm,55.495035,9.711485,25.0,Unmanaged deciduous woodland,2427872033-46889.JPG,0
618,2864910304,2020-09-17T00:00:00,2020.0,9.0,17.0,DK,Haarby,11746.0,Clitocybe agrestis Harmaja,Fungi,...,Assens,2864910304-138181,soil,Kirsten Munch Pontoppidan,55.225308,10.134014,15.0,lawn,2864910304-138181.JPG,1
3421,2238460880,2009-12-08T00:00:00,2009.0,12.0,8.0,DK,Eriksholm,11787.0,Clitocybe metachroa (Fr.) P.Kumm.,Fungi,...,Holbæk,2238460880-165982,soil,Tom Smidth,55.684960,11.801380,25.0,NaN,2238460880-165982.JPG,1
1037,2986455350,2020-11-25T00:00:00,2020.0,11.0,25.0,DK,Rantzausminde,63482.0,Clitocybe nebularis (Batsch) Quél.,Fungi,...,Svendborg,2986455350-221615,soil,Dan Schou,55.040664,10.551098,25.0,Mixed woodland (with coniferous and deciduous ...,2986455350-221615.JPG,0
2043,2237858476,2019-03-14T00:00:00,2019.0,3.0,14.0,DK,Jægerspris Slot,64062.0,Mycena tenerrima (Berk.) Sacc.,Fungi,...,Frederikssund,2237858476-224083,dead wood (including bark),Rasmus Riis-Hansen,55.851517,11.961568,25.0,Unmanaged deciduous woodland,2237858476-224083.JPG,1

In [12]:
import os
base_path = '/content/drive/MyDrive/Colab Notebooks/DF20M'
labels_path = os.path.join(base_path, 'labels')

In [15]:
def create_labels(df, output_dir):
    count = 0
    for _, row in df.iterrows():
        # get file, example: '2237852116-222680.JPG')
        filename = row['image_path'].split('/')[-1]
        name_only = os.path.splitext(filename)[0]

        label = row['mushroom_label']
        txt_path = os.path.join(output_dir, f"{name_only}.txt")

        # YOLO format: class x_center y_center width height
        with open(txt_path, 'w') as f:
            f.write(f"{label} 0.5 0.5 0.9 0.9")
        count += 1
    return count

In [16]:
labels_path = '/content/drive/MyDrive/labels/'
total_files = create_labels(test_df, labels_path)
print(f"Успішно створено {total_files} файлів розмітки у папці labels!")

Успішно створено 3640 файлів розмітки у папці labels!

In [14]:
mushrooms_map['Agaricus arvensis Schaeff.']

0

In [13]:
# clone repo YOLOv5
!git clone https://github.com/ultralytics/yolov5
%cd yolov5
# install requirements
!pip install -r requirements.txt

Cloning into 'yolov5'...
remote: Enumerating objects: 17822, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 17822 (delta 16), reused 6 (delta 6), pack-reused 17794 (from 2)
Receiving objects: 100% (17822/17822), 16.96 MiB | 23.89 MiB/s, done.
Resolving deltas: 100% (12144/12144), done.
/content/yolov5
Requirement already satisfied: gitpython>=3.1.30 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (3.1.46)
Requirement already satisfied: matplotlib>=3.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (3.10.0)
Requirement already satisfied: numpy>=1.23.5 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (2.0.2)
Requirement already satisfied: opencv-python>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (4.13.0.92)
Requirement already satisfied: pillow>=10.3.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 9)) (11.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 10)) (5.9.5)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 11)) (6.0.3)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 12)) (2.32.4)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 13)) (1.16.3)
Collecting thop>=0.1.1 (from -r requirements.txt (line 14))
  Downloading thop-0.1.1.post2209072238-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: torch>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 15)) (2.10.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 16)) (0.25.0+cu128)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 17)) (4.67.3)
Collecting ultralytics>=8.2.64 (from -r requirements.txt (line 18))
  Downloading ultralytics-8.4.19-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 27)) (2.2.2)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 28)) (0.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 42)) (26.0)
Requirement already satisfied: setuptools>=70.0.0 in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 43)) (75.2.0)
Collecting urllib3>=2.6.0 (from -r requirements.txt (line 51))
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython>=3.1.30->-r requirements.txt (line 5)) (4.0.12)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.3->-r requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->-r requirements.txt (line 12)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->-r requirements.txt (line 12)) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->-r requirements.txt (line 12)) (2026.1.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (2025.3.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.8.0->-r requirements.txt (line 15)) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.8.0->-r requirements.txt (line 15)) (1.3.5)
Requirement already satisfied: polars>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ultralytics>=8.2.64->-r requirements.txt (line 18)) (1.35.2)
Collecting ultralytics-thop>=2.0.18 (from ultralytics>=8.2.64->-r requirements.txt (line 18))
  Downloading ultralytics_thop-2.0.18-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->-r requirements.txt (line 27)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.4->-r requirements.txt (line 27)) (2025.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython>=3.1.30->-r requirements.txt (line 5)) (5.0.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars>=0.20.0->ultralytics>=8.2.64->-r requirements.txt (line 18)) (1.35.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.3->-r requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.8.0->-r requirements.txt (line 15)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.8.0->-r requirements.txt (line 15)) (3.0.3)
Downloading thop-0.1.1.post2209072238-py3-none-any.whl (15 kB)
Downloading ultralytics-8.4.19-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 52.8 MB/s eta 0:00:00
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.6/131.6 kB 17.7 MB/s eta 0:00:00
Downloading ultralytics_thop-2.0.18-py3-none-any.whl (28 kB)
Installing collected packages: urllib3, ultralytics-thop, thop, ultralytics
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed thop-0.1.1.post2209072238 ultralytics-8.4.19 ultralytics-thop-2.0.18 urllib3-2.6.3

In [15]:
yaml_content = f"""
path: /content/drive/MyDrive/labels
train: images/train
val: images/val

names:
  0: edible
  1: poisonous
"""

with open('/content/drive/MyDrive/data.yaml', 'w') as f:
    f.write(yaml_content)

print("Файл data.yaml успішно створено на твоєму Диску!")

Файл data.yaml успішно створено на твоєму Диску!

In [16]:
import yaml

# making configuration dict
data_config = {
    'path': '/content/drive/MyDrive',
    'train': 'Colab Notebooks/DF20M', # path for images
    'val': 'Colab Notebooks/DF20M',
    'nc': 2,
    'names': ['edible', 'poisonous']
}

with open('data.yaml', 'w') as f:
    yaml.dump(data_config, f)

In [32]:
import os
import shutil

# local structure
!mkdir -p /content/dataset/images
!mkdir -p /content/dataset/labels

# 1. copy labels
print("Копіюю лейбли...")
src_labels = '/content/drive/MyDrive/labels'
dst_labels = '/content/dataset/labels'
for f in os.listdir(src_labels):
    if f.endswith('.txt'):
        shutil.copy(os.path.join(src_labels, f), dst_labels)

# 2. make links for images
print("Створюю посилання на картинки...")
src_imgs = '/content/drive/MyDrive/Colab Notebooks/DF20M'
dst_imgs = '/content/dataset/images'

# make link for folder
!ln -s "{src_imgs}" /content/dataset/images_link

# get images names and make only for them links
labeled_names = [os.path.splitext(f)[0] for f in os.listdir(dst_labels)]
for name in labeled_names:
    for ext in ['.JPG', '.jpg']:
        img_path = os.path.join(src_imgs, name + ext)
        if os.path.exists(img_path):
            os.symlink(img_path, os.path.join('/content/dataset/images', name + ext))
            break

print(f"Готово! Знайдено лейблів: {len(os.listdir('/content/dataset/labels'))}")
print(f"Знайдено посилань на фото: {len(os.listdir('/content/dataset/images'))}")

Копіюю лейбли...
Створюю посилання на картинки...
Готово! Знайдено лейблів: 3640
Знайдено посилань на фото: 3640

In [33]:
import yaml

data_config = {
    'path': '/content/dataset',
    'train': 'images',
    'val': 'images',
    'nc': 2,
    'names': ['edible', 'poisonous']
}

with open('/content/yolov5/data/mushroom.yaml', 'w') as f:
    yaml.dump(data_config, f)

In [34]:
%cd /content/yolov5
!python train.py --img 640 --batch 32 --epochs 25 --data data/mushroom.yaml --weights yolov5s.pt

Выходные данные были обрезаны до нескольких последних строк (5000).
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01832   0.009551   0.006804         91        640:  61% 69/114 [02:46<02:01,  2.71s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01852   0.009563   0.006774         99        640:  61% 70/114 [02:48<01:58,  2.70s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01846   0.009568   0.006815         99        640:  62% 71/114 [02:50<01:43,  2.40s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01839   0.009558   0.006827         93        640:  63% 72/114 [02:53<01:43,  2.46s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01849   0.009567   0.006821         94        640:  64% 73/114 [02:54<01:32,  2.25s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01844   0.009565   0.006798        103        640:  65% 74/114 [02:57<01:36,  2.41s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01838    0.00955   0.006789         90        640:  66% 75/114 [03:00<01:38,  2.53s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01838   0.009539   0.006763         94        640:  67% 76/114 [03:03<01:39,  2.61s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0184   0.009545   0.006735        104        640:  68% 77/114 [03:05<01:28,  2.40s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01836   0.009531   0.006754         90        640:  68% 78/114 [03:07<01:20,  2.25s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01841   0.009517   0.006803         93        640:  69% 79/114 [03:10<01:25,  2.44s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01842   0.009507   0.006797         89        640:  70% 80/114 [03:11<01:11,  2.09s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01841   0.009509   0.006783         94        640:  71% 81/114 [03:15<01:31,  2.78s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01836    0.00949   0.006778         84        640:  72% 82/114 [03:17<01:17,  2.42s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01831   0.009494   0.006767         95        640:  73% 83/114 [03:19<01:18,  2.52s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01861   0.009516   0.006796        102        640:  74% 84/114 [03:21<01:05,  2.18s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01893   0.009523   0.006768        102        640:  75% 85/114 [03:23<01:05,  2.24s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01887   0.009514   0.006784         96        640:  75% 86/114 [03:25<00:57,  2.04s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01884   0.009508   0.006776         93        640:  76% 87/114 [03:28<01:06,  2.47s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0188    0.00949   0.006728         93        640:  77% 88/114 [03:31<01:07,  2.60s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01876   0.009477    0.00673         95        640:  78% 89/114 [03:33<01:02,  2.49s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0189   0.009468   0.007566         92        640:  79% 90/114 [03:37<01:04,  2.67s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0189    0.00945   0.007549         87        640:  80% 91/114 [03:38<00:54,  2.36s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01887   0.009441   0.007499         91        640:  81% 92/114 [03:41<00:54,  2.48s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01885   0.009429   0.007493         92        640:  82% 93/114 [03:44<00:53,  2.55s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01885   0.009426   0.007504         91        640:  82% 94/114 [03:47<00:56,  2.81s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01935   0.009425   0.007524         91        640:  83% 95/114 [03:49<00:45,  2.40s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0193   0.009444   0.007498        108        640:  84% 96/114 [03:52<00:47,  2.64s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01948   0.009438   0.007506         92        640:  85% 97/114 [03:53<00:36,  2.16s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G     0.0194   0.009429   0.007514         90        640:  86% 98/114 [03:56<00:37,  2.36s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01933   0.009434   0.007516        100        640:  87% 99/114 [03:58<00:33,  2.24s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01929   0.009422   0.007488         89        640:  88% 100/114 [04:01<00:38,  2.75s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01926   0.009433   0.007503        104        640:  89% 101/114 [04:03<00:31,  2.40s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01924   0.009442   0.007522        101        640:  89% 102/114 [04:06<00:29,  2.44s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01922   0.009437   0.007491         91        640:  90% 103/114 [04:07<00:23,  2.16s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01918   0.009429   0.007493         96        640:  91% 104/114 [04:10<00:23,  2.36s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01911   0.009424   0.007489         95        640:  92% 105/114 [04:13<00:24,  2.67s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01928   0.009415   0.007479         92        640:  93% 106/114 [04:17<00:23,  2.89s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01926   0.009436   0.007481         97        640:  94% 107/114 [04:19<00:18,  2.66s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01946   0.009444   0.007487         95        640:  95% 108/114 [04:21<00:15,  2.53s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01958    0.00944   0.007554         86        640:  96% 109/114 [04:23<00:12,  2.42s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01951   0.009443   0.007558        101        640:  96% 110/114 [04:25<00:09,  2.28s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01943   0.009431   0.007569         92        640:  97% 111/114 [04:28<00:07,  2.58s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01938   0.009416    0.00756         81        640:  98% 112/114 [04:32<00:05,  2.78s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01934    0.00941   0.007549         93        640:  99% 113/114 [04:34<00:02,  2.60s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       3/24      11.7G    0.01929   0.009399   0.007544         56        640: 100% 114/114 [04:35<00:00,  2.42s/it]
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100% 57/57 [02:13<00:00,  2.33s/it]
                   all       3638       3638      0.947      0.488      0.499      0.362

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
  0% 0/114 [00:00<?, ?it/s]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01521   0.008314   0.008294         89        640:   1% 1/114 [00:00<00:50,  2.24it/s]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01373   0.008698   0.008655         89        640:   2% 2/114 [00:00<00:49,  2.27it/s]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01311   0.008539   0.008027         95        640:   3% 3/114 [00:01<00:50,  2.22it/s]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01364   0.009212   0.007846        103        640:   4% 4/114 [00:01<00:46,  2.38it/s]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01737   0.009379    0.02347         94        640:   4% 5/114 [00:07<04:13,  2.33s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01671   0.009437    0.02039         97        640:   5% 6/114 [00:08<03:15,  1.81s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01612   0.009426     0.0183         97        640:   6% 7/114 [00:14<05:40,  3.18s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01566   0.009346    0.01702         97        640:   7% 8/114 [00:14<04:02,  2.29s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01547   0.009276    0.01668         86        640:   8% 9/114 [00:18<04:50,  2.77s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01545   0.009402    0.01549        103        640:   9% 10/114 [00:18<03:32,  2.04s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01546   0.009305    0.01456         90        640:  10% 11/114 [00:22<04:06,  2.39s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01526   0.009211    0.01413         95        640:  11% 12/114 [00:23<03:32,  2.08s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01516   0.009136    0.01338         93        640:  11% 13/114 [00:27<04:36,  2.74s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01528   0.009191     0.0128         96        640:  12% 14/114 [00:29<03:55,  2.36s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01534   0.009147    0.01236         93        640:  13% 15/114 [00:31<04:04,  2.47s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01541   0.009202    0.01206        100        640:  14% 16/114 [00:33<03:40,  2.25s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01549   0.009148    0.01179        100        640:  15% 17/114 [00:36<03:45,  2.33s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):
       4/24      11.7G    0.01541   0.009147    0.01145         97        640:  16% 18/114 [00:37<03:21,  2.10s/it]/content/yolov5/train.py:414: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(amp):

In [35]:
import shutil
# best model
shutil.copy('/content/yolov5/runs/train/exp4/weights/best.pt', '/content/drive/MyDrive/mushroom_model_best.pt')
print("successfully saved to Google Drive!")

successfully saved to Google Drive!

In [38]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source гриб.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб.jpg: 640x512 1 poisonous, 46.9ms
Speed: 0.6ms pre-process, 46.9ms inference, 197.2ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp3

In [39]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source гриб2.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб2.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб2.jpg: 640x640 1 poisonous, 10.3ms
Speed: 0.6ms pre-process, 10.3ms inference, 130.3ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp4

In [41]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source гриб3.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб3.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб3.jpg: 480x640 1 poisonous, 50.8ms
Speed: 0.7ms pre-process, 50.8ms inference, 168.9ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp6

In [43]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source гриб4.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб4.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб4.jpg: 448x640 1 poisonous, 50.6ms
Speed: 0.8ms pre-process, 50.6ms inference, 138.6ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp8

In [44]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.75 --source гриб4.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб4.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.75, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб4.jpg: 448x640 (no detections), 31.9ms
Speed: 0.6ms pre-process, 31.9ms inference, 30.2ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp9

In [45]:
!python detect.py --weights runs/train/exp4/weights/best.pt --img 640 --conf 0.25 --source гриб4.jpg

detect: weights=['runs/train/exp4/weights/best.pt'], source=гриб4.jpg, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_format=0, save_csv=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v7.0-460-g3fb11111 Python-3.12.12 torch-2.10.0+cu128 CUDA:0 (Tesla T4, 14913MiB)

Fusing layers...
Model summary: 157 layers, 7015519 parameters, 0 gradients, 15.8 GFLOPs
image 1/1 /content/yolov5/гриб4.jpg: 448x640 1 poisonous, 39.0ms
Speed: 0.7ms pre-process, 39.0ms inference, 109.7ms NMS per image at shape (1, 3, 640, 640)
Results saved to runs/detect/exp10

In [46]:
import shutil
from google.colab import files


shutil.make_archive('mushroom_results', 'zip', '/content/yolov5/runs/train/exp4')

files.download('mushroom_results.zip')